name: watersupply_kamarain
channels:
  - conda-forge
dependencies:
  - python=3.10
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - optuna=4.0.0
  - requests=2.32.3
  - cdsapi=0.6.1
  - fiona=1.9.5
  - gdal=3.7.3
  - geopandas=0.14.1
  - joblib=1.3.2
  - netCDF4=1.6.5
  - numpy=1.26.2
  - pandas=2.1.3
  - pip=23.3
  - pyproj=3.6.1
  - rasterio=1.3.9
  - rioxarray=0.15.0
  - scikit-learn=1.3.2
  - scipy=1.11.4
  - shapely=2.0.2
  - shap=0.45.1
  - statsmodels=0.14.0
  - xarray=2023.11.0
  - pip:
      - wsfr_download@git+https://github.com/drivendataorg/water-supply-forecast-rodeo-runtime.git#egg=pkg&subdirectory=data_download
