title: Forecast Report {{< var site_short >}} {{< var issue_date >}}
format:
    pdf:
      documentclass: scrartcl
      page-size: Letter
      margin: 1in
      fontsize: 11pt
      linestretch: 1
      keep-tex: true
      geometry: "left=1in, top=1in, right=1in, bottom=1in"
      echo: false
      message: false
      warning: false
      error: false
      include-in-header: header.tex

execute:
  echo: false
  warning: false
  message: false
  error: false
