# Config file for bulk downloading feature data for Hindcast test years
# To be used with `python -m wsfr_download bulk <path-to-this-file>`
# See `python -m wsfr_download bulk --help` for details.
#
# To bulk download feature data for training, copy this file and set the
# forecast years and data sources that you need.

forecast_years: [ 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2006, 2008, 2010, 2012, 2014, 2016, 2018, 2020, 2022 ]
skip_existing: true
data_sources:
  # Antecedent streamflow
#  - name: usgs_streamflow
#  # Snowpack
  - name: snotel
#  - name: snodas
#  - name: cdec
#  # Climate and weather
#  - name: cpc_outlooks
#  # Drought/moisture conditions
#  - name: grace_indicators
#  - name: pdsi
#  # Teleconnections
#  - name: mjo
#  - name: nino_regions_sst
#  - name: oni
#  - name: pdo
#  - name: pna
#  - name: soi
